image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  github_token:
    secure: Ifn++YqNoay4zsQIekOlTGhqsu6UUXOpRoNKkI8IVJmtT3ctBBAuKO9vHfbmkytC

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $lastTag = git describe --abbrev=0
      Set-AppveyorBuildVariable -Name 'LAST_TAG' -Value $lastTag
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
      
  - cmd: msbuild Sawmill.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal

  - cmd: cinst docfx

  - ps: |
      git config --global credential.helper store
      Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
      git config --global user.email "benhodgson91@gmail.com"
      git config --global user.name "AppVeyor build server"
      git config --global core.safecrlf false

build:
  project: Sawmill.sln
  verbosity: minimal

after_build:
  - cmd: docfx Sawmill.Docs/docfx.json
  
after_test:
  - ps: dir "**\bin\$env:CONFIGURATION\*\*.xml" | foreach { dotnet run --no-build --configuration "$env:CONFIGURATION" --project Sawmill.DocMunger\Sawmill.DocMunger.csproj "Sawmill\bin\$env:CONFIGURATION\netstandard2.0\Sawmill.xml" $_.FullName }
  - cmd: msbuild Sawmill.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: Sawmill.Docs/_site

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: R0Op0GMj2Wvup7yDYCmpbiNHKFbZgPcWMHlKiw1BvlYfJv1v8hGT8nfouIF5KRfk
  on:
    appveyor_repo_tag: true

on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master' -or $env:APPVEYOR_REPO_TAG -eq 'true') {
        git clone https://github.com/benjamin-hodgson/Sawmill.git -q --depth 1 --branch gh-pages gh-pages
        Remove-Item "gh-pages\$env:APPVEYOR_REPO_BRANCH" -Recurse -ErrorAction Ignore
        Copy-Item Sawmill.Docs\_site -Destination "gh-pages\$env:APPVEYOR_REPO_BRANCH" -Recurse -Container
        cd gh-pages
        git add "$env:APPVEYOR_REPO_BRANCH"
        (gc index.html) -replace 'https://www.benjamin.pizza/Sawmill/[^/]*/', "https://www.benjamin.pizza/Sawmill/$env:LAST_TAG/" | Out-File index.html
        git add index.html
        git commit --allow-empty -m "Update gh-pages"
        git push -q
      }
