image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  github_token:
    secure: Ifn++YqNoay4zsQIekOlTGhqsu6UUXOpRoNKkI8IVJmtT3ctBBAuKO9vHfbmkytC

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $lastTag = git describe --abbrev=0
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
      
  - cmd: msbuild Sawmill.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal

  - cmd: cinst docfx

  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_token):x-oauth-basic@github.com`n"
  - cmd: git config --global user.email "benhodgson91@gmail.com"
  - cmd: git config --global user.name "AppVeyor build server"

build:
  project: Sawmill.sln
  verbosity: minimal

after_build:
  - cmd: docfx Sawmill.Docs/docfx.json
  
after_test:
  - ps: dir "**\bin\$env:CONFIGURATION\*\*.xml" | foreach { dotnet run --no-build --configuration "$env:CONFIGURATION" --project Sawmill.DocMunger\Sawmill.DocMunger.csproj "Sawmill\bin\$env:CONFIGURATION\netstandard2.0\Sawmill.xml" $_.FullName }
  - cmd: msbuild Sawmill.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: Sawmill.Docs/_site

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: R0Op0GMj2Wvup7yDYCmpbiNHKFbZgPcWMHlKiw1BvlYfJv1v8hGT8nfouIF5KRfk
  on:
    appveyor_repo_tag: true

on_success:
  - cmd: git clone https://github.com/benjamin-hodgson/Sawmill.git --depth 1 --branch gh-pages gh-pages
  - cmd: if exist "gh-pages\%APPVEYOR_REPO_BRANCH%" rm -r "gh-pages\%APPVEYOR_REPO_BRANCH%"
  - cmd: echo d | xcopy Sawmill.Docs\_site "gh-pages\%APPVEYOR_REPO_BRANCH%" /e
  - cmd: cd gh-pages
  - cmd: git add "%APPVEYOR_REPO_BRANCH%"
  - cmd: git commit --allow-empty -m "Update gh-pages"
  - cmd: git push
