configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/v2.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
  - ps: .\dotnet-install.ps1 -Version 2.0.0

before_build:
  - ps: |
      $lastTag = git describe --abbrev=0
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build --configuration %CONFIGURATION%

test_script:
  - cmd: dotnet test --configuration %CONFIGURATION% Sawmill.Tests\Sawmill.Tests.csproj

after_test:
  - cmd: dotnet pack Sawmill\Sawmill.csproj --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack Sawmill.Newtonsoft.Json\Sawmill.Newtonsoft.Json.csproj --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack Sawmill.Microsoft.CodeAnalysis\Sawmill.Microsoft.CodeAnalysis.csproj --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack Sawmill.Microsoft.CodeAnalysis.CSharp\Sawmill.Microsoft.CodeAnalysis.CSharp.csproj --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: dotnet pack Sawmill.Microsoft.CodeAnalysis.VisualBasic\Sawmill.Microsoft.CodeAnalysis.VisualBasic.csproj --configuration %CONFIGURATION% --output ..\nupkgs --include-symbols --version-suffix %APPVEYOR_BUILD_NUMBER%

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: DiGJunoltKKtbdv848PTwuhNSkpZdGn5MLOwn3TTXjnr/D/gmbCGCOgzHICN7yGk
  on:
    appveyor_repo_tag: true
