image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      $lastTag = git describe --abbrev=0
      Update-AppveyorBuild -Version "$lastTag-$env:APPVEYOR_BUILD_NUMBER"
  - cmd: msbuild Sawmill.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal

build:
  project: Sawmill.sln
  verbosity: minimal
  
after_test:
  - ps: dir "**\bin\$env:CONFIGURATION\*\*.xml" | foreach { dotnet run --no-build --configuration "$env:CONFIGURATION" --project Sawmill.DocMunger\Sawmill.DocMunger.csproj "Sawmill\bin\$env:CONFIGURATION\netstandard2.0\Sawmill.xml" $_.FullName }
  - cmd: msbuild Sawmill.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: R0Op0GMj2Wvup7yDYCmpbiNHKFbZgPcWMHlKiw1BvlYfJv1v8hGT8nfouIF5KRfk
  on:
    appveyor_repo_tag: true
