image: Visual Studio 2019
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  github_token:
    secure: Ifn++YqNoay4zsQIekOlTGhqsu6UUXOpRoNKkI8IVJmtT3ctBBAuKO9vHfbmkytC

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      Invoke-WebRequest https://github.com/benjamin-hodgson/BuildScripts/archive/master.zip -OutFile BuildScripts.zip
      Expand-Archive BuildScripts.zip -Destination .
      mv BuildScripts-master BuildScripts

  - ps: .\BuildScripts\appveyor\InitBuildNumber.ps1
  - cmd: msbuild Sawmill.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal
  - cmd: cinst docfx
  - ps: .\BuildScripts\appveyor\ConfigureGit.ps1

build:
  project: Sawmill.sln
  verbosity: minimal
  
after_test:
  - cmd: dotnet run --configuration %CONFIGURATION% --project Sawmill.Bench\Sawmill.Bench.csproj
  - cmd: msbuild Sawmill.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal
  - cmd: docfx Sawmill.Docs/docfx.json

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: BenchmarkDotNet.Artifacts
  - path: Sawmill.Docs/_site

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: lplusvcG1mQrwcwXWVEf6HLrleyF405L0VlV5wLwOgn9lSimkOif0TEOWMCV+okc
  on:
    appveyor_repo_tag: true

on_success:
  - ps: .\BuildScripts\appveyor\PushDocs.ps1
